name: example
description: example local-first app

publish_to: 'none'

environment:
  sdk: ">=2.15.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  replicore:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter